// Validation Middleware Exports
// This file is auto-generated by the PERN-Fortress CLI

import { Request, Response, NextFunction } from 'express';
import { validationResult } from 'express-validator';

// Common validation utilities
export const handleValidationErrors = (
  req: Request,
  res: Response,
  next: NextFunction
): void | Response => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    return res.status(400).json({
      error: 'Validation failed',
      details: errors.array(),
      status: 400,
      timestamp: new Date().toISOString(),
    });
  }

  next();
};

// Pagination validation
export const validatePagination = [
  require('express-validator')
    .query('limit')
    .optional()
    .isInt({ min: 1, max: 100 })
    .withMessage('Limit must be between 1 and 100'),
  require('express-validator')
    .query('offset')
    .optional()
    .isInt({ min: 0 })
    .withMessage('Offset must be a non-negative integer'),
];

// Auto-generated exports will be added below
export {
  validateCreateUsers,
  validateUpdateUsers,
  validateGetUsersById,
} from './users';
export {
  validateCreateProducts,
  validateUpdateProducts,
  validateGetProductsById,
} from './products';
export {
  validateCreateBook,
  validateUpdateBook,
  validateGetBookById,
} from './book';
